### ISSUE TITLE
Sveltekit prefetching is not working

### ISSUE THREAD

**Issue by yousufiqbal** [svemix/svemix#11]
Prefetching of routes using `sveltekit:prefetch` is not working on anchor elements `<a sveltekit:prefetch href="/users">Users</a>`

**Comment by pixelmund** [comment]
Hey are you sure this is an issue within svemix? Because i can't seem to get `sveltekit:prefetch` working on a fresh `npm init svelte@next`, so the problem might be in kit itself.

**Comment by RA9** [comment]
> Prefetching of routes using `sveltekit:prefetch` is not working on anchor elements `<a sveltekit:prefetch href="/users">Users</a>`

Shouldn't it be `rel="prefetch"`?
