### ISSUE TITLE
Respect SvelteKit Config for `kit.files.routes`

### ISSUE THREAD

**Issue by Acmion** [svemix/svemix#27]
The route directory can be changed with SvelteKit like this:
```
const config = 
{
    kit: 
    {
        files: 
        {
            routes: "src/web" // or whatever
        }
    }
}
```

However, this configuration will essentially disable Svemix, because the route directory is hardcoded as `src/routes`. 

This can be fixed by amending the config like this:
```
const config = 
{
    svemix: 
    {
        routes: "src/web"
    },
    kit: 
    {
        files: 
        {
            routes: "src/web" // or whatever
        }
    }
}
```

However, the fix is not documented, nor is the property `routes` a part of [Svemix_Config_Object](https://github.com/svemix/svemix/blob/main/src/lib/plugin/load_config.ts). Although, the property `routes` is a part of the [defaultConfig](https://github.com/svemix/svemix/blob/main/src/lib/plugin/load_config.ts), which is why the problem can be fixed.

Still, the most sensible way to go about this would be just to respect the configuration of `kit.files.routes`.

**Comment by pixelmund** [comment]
Hey, that seems fairly reasonable to me. I think i can get the required changes in very quickly, since we're already loading the config this should be pretty straight forward.
