### ISSUE TITLE
Document Limitations of Svemix

### ISSUE THREAD

**Issue by Acmion** [svemix/svemix#29]
Svemix is a great plugin, but it does have it's limitations. These limitations should be documented.

Some important limitations:
1. The `loader` responses are JSON serialized, which causes overhead.
2. The populated objects (e.g. `export var book: Book`) are not really of the specified type, but rather just JS data objects. This means that one can not call type functions, for example, `book.getYearsSincePublication()`. 
3. An extra request is made to the server.

**Comment by pixelmund** [comment]
Closed by #31
