### ISSUE TITLE
Security Issue (Relatively Minor)

### ISSUE THREAD

**Issue by Acmion** [svemix/svemix#30]
I detected a relatively minor security issue in Svemix, but I will not post it here. Could I contact you in some other way?

**Comment by pixelmund** [comment]
You can contact me via E-Mail: pixelmund@gmail.com

**Comment by pixelmund** [comment]
You can contact me via E-Mail: pixelmund@gmail.com

**Comment by Acmion** [comment]
@pixelmund Got it. You can remove the email from the comment.

**Comment by pixelmund** [comment]
Closed by #31
